### ISSUE TITLE
Feature request: Weapon restictions

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [NockyCZ/CS2-Deathmatch#10]
Would be great if you could limit the amount of weapons on a server. For example, I only want to allow one AWP in each team. No more than that. So two in total.

And then maybe add support for VIP/ADMINS so they can have their own pool of restricted weapons. So maybe I want to allow VIPS to be able to pick one AWP extra in each team.

So in total, it would be 1+1 in each team in above scenario.

The way the config worked in CSGO was like this:

            "Primary"
            {
                "weapon_ak47"          "-1"
                "weapon_m4a1"          "-1"
                "weapon_m4a1_silencer" "-1"
                "weapon_sg556"         "-1"
                "weapon_aug"           "-1"
                "weapon_galilar"       "-1"
                "weapon_awp"         "2"
            }
            
            "Secondary"
            {
                "weapon_glock"         "-1"
                "weapon_p250"          "-1"
                "weapon_cz75a"         "-1"
                "weapon_usp_silencer"  "-1"
		"weapon_deagle"        "-1"
                "weapon_fiveseven"     "-1"
                "weapon_revolver"      "-1"
                "weapon_elite"         "-1"
                "weapon_tec9"          "-1"
		"weapon_hkp2000"       "-1"
            }

So the amount in "-1" would be per team, to support both TDM and FFA. -1 being no restriction. But maybe if FFA is enabled, it should be for the whole server rather than team.

Not sure how to add the VIP feature, tho. Maybe a whole different section for VIP/ADMIN weapons?

            "VIP Primary"
            {
                "weapon_awp"          "1"
            }
            
            "VIP Secondary"
            {
            }

Or maybe just add a 2nd value like this:

            "Primary"
            {
                "weapon_ak47"          "-1" "0"
                "weapon_m4a1"          "-1" "0"
                "weapon_m4a1_silencer" "-1" "0"
                "weapon_sg556"         "-1" "0"
                "weapon_aug"           "-1" "0"
                "weapon_galilar"       "-1" "0"
                "weapon_awp"         "2" "1"
            }

**Comment by NockyCZ** [comment]
Added in v1.0.3
