### ISSUE TITLE
Random guns after joining the server

### ISSUE THREAD

**Issue by shaikhnedab** [NockyCZ/CS2-Deathmatch#17]
if player has not selected any gun after joining the server using !gun command the player will get random primary and secondary weapon on each respawn. can you fix this?

**Comment by NockyCZ** [comment]
This is not a bug, its intentional. However, i can add an option to the config to disable random weapons when the player doesnt have selected weapons

**Comment by shaikhnedab** [comment]
that  would be nice

**Comment by NockyCZ** [comment]
Added in v1.0.3
