### ISSUE TITLE
Bug custom mode pistol

### ISSUE THREAD

**Issue by szogun1910** [NockyCZ/CS2-Deathmatch#19]
Hey, I noticed that when we add only pistol mode and set the default weapon on it as usp, it gets osona removed from the player and a message pops up in chat [Deathmatch] Your secondary weapon has been set to USP
[Deathmatch] Weapon P2000 is disabled in this mode!

**Comment by NockyCZ** [comment]
https://github.com/NockyCZ/CS2-Deathmatch?tab=readme-ov-file#creating-custom-modes
```
List of weapons that must be in the same list:
weapon_usp_silencer and weapon_hkp2000
weapon_mp5sd and weapon_mp7
```
