### ISSUE TITLE
"No spawn points found for this map!" - Workshop Map

### ISSUE THREAD

**Issue by Hausi91** [NockyCZ/CS2-Deathmatch#2]
Hi, im facing an issue with the custom spawn points.
The Plugin is able to create the "spawn point JSON" in the "Spawn Editor" but doesn't  find the file when playing the game.
Console: "[Deathmatch] No spawn points found for this map! (Deathmatch/spawns/scoutzknivez.json)".
Issue present in both v1.0 & v1.1.
JSON path: /addons/counterstrikesharp/plugins/Deathmatch/spawns/scoutzknivez.json
Map: https://steamcommunity.com/sharedfiles/filedetails/?id=3071655169

**Comment by Hausi91** [comment]
mp_randomspawn trolled me

**Comment by NockyCZ** [comment]
This will be fixed in the new update

**Comment by NockyCZ** [comment]
I tried creating spawn points on a workshop map, and it works :)
