### ISSUE TITLE
Weapon buy menu

### ISSUE THREAD

**Issue by Mini-chill** [NockyCZ/CS2-Deathmatch#20]
Hello, in newest plugin version there is change that player have to type in chat to choose weapon, is it possible to turn on regular buy menu as it was in previous plugin versions? 
It' s much more easier for players to choose from buy menu not to type in chat. 

Maybe there is cvar for that but I didn't find.

**Comment by NockyCZ** [comment]
When valve fixes the convar mp_items_prohibited, i will add it back

**Comment by Mini-chill** [comment]
> When valve fixes the convar mp_items_prohibited, i will add it back

They didn't fix this?

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.0.5
