### ISSUE TITLE
Server crash & Infinite players respawn

### ISSUE THREAD

**Issue by St3rMi88** [NockyCZ/CS2-Deathmatch#23]
Hello, I installed your plugin successfully. Unfortunately it continues to crash the server, plus players continue to automatically respawn every 10-15 seconds. How can I fix it?

**Comment by NockyCZ** [comment]
OS? And any errors ?

**Comment by St3rMi88** [comment]
> OS? And any errors ?

I am running the game server on a Linux Ubuntu 22.04 LTS machine, with:

- Metamod 2.X Dev Build
- CounterStrikeSharp v166
- Your DM plugin v1.0.4

I don't see any errors, just the players respawning all together every 10-15 seconds.

You can test it by yourself: **136.243.18.117:28410**

**Comment by NockyCZ** [comment]
You have timelimit 0,
