### ISSUE TITLE
Music on gamemode change

### ISSUE THREAD

**Issue by Mini-chill** [NockyCZ/CS2-Deathmatch#26]
Hello, I can't find how to disable or set volume on gamemode change. 
Is it even possible to disable it or turn volume down?

**Comment by NockyCZ** [comment]
If you want to disable it, leave the path empty. And players can change the volume snd_toolvolume 0.1 command

**Comment by Mini-chill** [comment]
Sorry, my deathmatch config wasn't updated to latest version, that' s why I couldn't find how to disable music. 

Thank you!
