### ISSUE TITLE
spawn system help - and feature request?

### ISSUE THREAD

**Issue by y3request** [NockyCZ/CS2-Deathmatch#29]
I have an fy_map I added all the spawns, edit the spawn distance from enemy, edit the spawn time all in the configs.
36 spawns 24 slot server. I fill it with bots to max to limit test.

_My problem is_, bots/me keep spawning inside of each other. I cant figure out how to avoid this. I know fy maps are small, but valve's default DM mode doesn't do this, but I like your plugin a lot so I would like to get your plugin working flawlessly on my server.
If I use spawns that I add in plugin spawn editor, or the default spawns the map creator put for DM it happens.

**Any ideas on what I can do? Maybe add an option to the plugin that delays spawning until a position is available?**

**Comment by NockyCZ** [comment]
Can you send me your config file?

**Comment by y3request** [comment]
i set the distance back to default I believe because nothing was working (10,100,1000,etc) but here it is.

`// This configuration was automatically generated by CounterStrikeSharp for plugin 'Deathmatch', at 2024/03/27 08:01:12
{
  "Gameplay Settings": {
    "Free For All": true,
    "Custom Modes": false,
    "Random Selection Of Modes": false,
    "Map Start Custom Mode": 0,
    "New Mode Countdown": 0,
    "Check Enemies Distance": true,
    "Distance From Enemies for Respawn": 500,
    "Default Weapons": 2,
    "Switch Weapons": true,
    "Allow Buymenu": true,
    "Use Default Spawns": false,
    "Respawn Players After New Mode": false
  },
  "General Settings": {
    "Hide Round Seconds": true,
    "Block Radio Messages": true,
    "Remove Breakable Entities": false,
    "Remove Decals After Death": true,
    "Force Map End": false
  },
  "Sounds Settings": {
    "Weapon Cant Equip Sound": "sounds/ui/weapon_cant_buy.vsnd_c",
    "New Mode Sound": "sounds/music/3kliksphilip_01/bombtenseccount.vsnd_c"
  },
  "Custom Commands": {
    "Deatmatch Menu Commands": "dm,deathmatch,d",
    "Weapons Select Commands": "gun,weapon,w,g",
    "Weapons Select Shortcuts": "weapon_ak47:ak,weapon_m4a1:m4,weapon_awp:awp,weapon_usp_silencer:usp,weapon_glock:glock,weapon_deagle:deagle"
  },
  "Players Gameplay Settings": {
    "VIP_flag": "@css/vip",
    "respawn_time": 2.5,
    "VIP_respawn_time": 3,
    "spawn_protection_time": 3,
    "VIP_spawn_protection_time": 3,
    "reffil_ammo_kill": true,
    "VIP_reffil_ammo_kill": true,
    "reffil_ammo_headshot": true,
    "VIP_reffil_ammo_headshot": true,
    "refill_health_kill": 20,
    "VIP_refill_health_kill": 20,
    "refill_health_headshot": 40,
    "VIP_refill_health_headshot": 40
  },
  "Client Preferences": {
    "Kill Sound": {
      "Enabled": true,
      "Sound path": "sounds/ui/armsrace_kill_01.vsnd_c",
      "Default value": true,
      "Only for VIP": false
    },
    "Headshot Kill Sound": {
      "Enabled": true,
      "Sound path": "sounds/buttons/bell1.vsnd_c",
      "Default value": true,
      "Only for VIP": false
    },
    "Knife Kill Sound": {
      "Enabled": true,
      "Sound path": "sounds/ui/armsrace_final_kill_knife.vsnd_c",
      "Default value": true,
      "Only for VIP": false
    },
    "Hit Sound": {
      "Enabled": true,
      "Sound path": "sounds/ui/csgo_ui_contract_type2.vsnd_c",
      "Default value": true,
      "Only for VIP": false
    },
    "Only Headshot": {
      "Enabled": true,
      "Default value": false,
      "Only for VIP": false
    },
    "Hud Messages": {
      "Enabled": true,
      "Default value": true,
      "Only for VIP": false
    }
  },
  "ConfigVersion": 1
}`

**Comment by NockyCZ** [comment]
Even if you have a distance check 500, do the players spawns still inside each other?

**Comment by NockyCZ** [comment]
When they spawn inside each other, it should write to the server console:
`[Deathmatch] Player Rebel was respawned, but no available spawn point was found! Therefore, a random spawn was selected.`

**Comment by y3request** [comment]
> Even if you have a distance check 500, do the players spawns still inside each other?

yes, that is why I started tinkering with it at first.

> When they spawn inside each other, it should write to the server console:
> `[Deathmatch] Player Rebel was respawned, but no available spawn point was found! Therefore, a random spawn was selected.`

Eventually console will say that message

Maybe it should do this instead.
Hud message, "No safe spawn, please wait..." then push out the player after one is "safe" if possible

**Comment by NockyCZ** [comment]
Then you can try set check distance to smaller value, for example 100. Because fy_snow is a small map

And then check the console again to see if it still says errors

**Comment by y3request** [comment]
Ok thank you! I will try soon and let you know. I am currently dodging hackers in premier matchmaking.

**Comment by NockyCZ** [comment]
Okay 😂

**Comment by y3request** [comment]
I am testing soon, compiling a map. I noticed something else just now tho. On my map that has a particle for snow, that works normally. With your deathmatch plugin it doesnt snow on my level. All particle systems are gone.

I have it OnMapSpawn start SnowParticle, but I think the way people are spawning with the plugin is different or something. I think I can fix this myself by adding a new trigger tho in consideration for the plugin.

**Comment by y3request** [comment]
Can confirm lower value has fixed it. Thanks man. I went not low enough I think. No error in console.

**Comment by NockyCZ** [comment]
Great! :)
