### ISSUE TITLE
Feature Request: Spawn protection glow

### ISSUE THREAD

**Issue by y3request** [NockyCZ/CS2-Deathmatch#30]
Could you add a glow spawn protection around the player or simply change their model color until spawn protection has ended?

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.3

**Comment by y3request** [comment]
**I have it set to** 
"Spawn Protection Color": "#FC0303"

**and my spawn protection time is** 
"VIP_respawn_time": 2.5,
"spawn_protection_time": 2.5,

But i dont see it, on myself or the bots. Is it because the bots buy too fast and I cannot see it in first person on myself?

**Comment by NockyCZ** [comment]
Bots do not have spawn protection and yeah you cant see the protection color on yourself
