### ISSUE TITLE
Feature request: Expose custom modes values

### ISSUE THREAD

**Issue by weeestar** [NockyCZ/CS2-Deathmatch#31]
hello!

Could it be possible to expose custom modes timeleft and timeelapsed, names or alias values in order to use it in center messages? 

I'd like to display something like:

Current mode: Pistols HS only
Next mode: Rifles in 3:28

Thanks for your great job!

**Comment by NockyCZ** [comment]
This is not possible because a new mode is selected when the current mode ended

**Comment by weeestar** [comment]
Cannot we access to the index of the current mode and navigate in the list to get the informations?

**Comment by NockyCZ** [comment]
It doesnt matter because someone has `Random Selection Of Modes` enabled and someone has it disabled

**Comment by weeestar** [comment]
I've forgot this feat, u're right! haha :(
