### ISSUE TITLE
server language spawn bug

### ISSUE THREAD

**Issue by xlenonz** [NockyCZ/CS2-Deathmatch#33]
Hello,

addons/counterstrikesharp/configs/plugins/Deathmatch/Deathmatch.json
with setting => "Use Default Spawns": false,"

if addons/counterstrikesharp/configs/core.json
ServerLanguage is en 
no problem

if ServerLanguage different then "en" like tr
cannot spawn on map, player always dropping

an unusual error cannot figure out why, can you help about it ?

**Comment by NockyCZ** [comment]
I will look at it

**Comment by gabrielsdelima75** [comment]
same problem.

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.2
