### ISSUE TITLE
Server crash when adding bots

### ISSUE THREAD

**Issue by asdfxD** [NockyCZ/CS2-Deathmatch#4]
server crashes when adding bots.

**Comment by NockyCZ** [comment]
error log? linux or windows ?

**Comment by asdfxD** [comment]
there is no error log in cssharp, i use linux, when adding a bot the console freezes.

after 20 seconds or so:

WatchDog! Server took too long to process (probably infinite loop)
Watchdog timeout exceeded, exiting
 0 Watchdog timeout exceeded, exiting

than it crash and restarts.

**Comment by NockyCZ** [comment]
Try it with the latest version please :)
