### ISSUE TITLE
New mode countdown timer not working

### ISSUE THREAD

**Issue by skyprah** [NockyCZ/CS2-Deathmatch#41]
DM: v1.1.5
CSS: 239
Metamod: 1293
OS: Windows

Took me a while to figure out that Hide New Mode Countdown to false would enable 2 hud boxes, seems a bit confusing. I am trying to get just the bottom countdown to work only when 10 seconds remaining but it seems you're stuck with only using the   "Hud.NewModeStarting" from lang that doesn't support variables.

There should be a setting to have the bottom hud display the countdown within x seconds but also with the variables like {NEXTMODE}. Or atleast a seperate custom mode. Or at least a 2nd "CenterMessageTextBottom" for each custom mode so that variables can be used without having to have the hud on the screen always. 

Thanks

**Comment by NockyCZ** [comment]
Do you mean add support for {NEXTMODE} in Hud.NewModeStarting ?

**Comment by skyprah** [comment]
> Do you mean add support for {NEXTMODE} in Hud.NewModeStarting ?

Yes but the main hud with html should be able to appear only after X seconds as per the cvar. But I was unable to do this as it just stayed on constantly which made me try the Hud.NewModeStarting and disable the main one. If you can make a setting for the main html hud to appear X seconds before new mode, that would be ideal the best solution.

**Comment by NockyCZ** [comment]
Already added/fixed in the latest update
