### ISSUE TITLE
People spawning at the same place.

### ISSUE THREAD

**Issue by MaCoRko** [NockyCZ/CS2-Deathmatch#43]
Hello,

I have the issue where the people spawns at the same place all the time.Example: We are 7 on server to test it and map is de_dust2, i die on short and spawn in lower, next couple of times wherever i die i spawn in the lower, this happens on every map i tried to: dust, mirage, vertigo... same thing. here is my config.

https://pastebin.com/DQRbuPM3

I even tried with the default config and it happens aswell on the default.

**Comment by NockyCZ** [comment]
@MaCoRko Any errors in the console?

**Comment by MaCoRko** [comment]
> @MaCoRko Any errors in the console?

No it was all working smoothly

**Comment by NockyCZ** [comment]
And server gamemode? Casual or Deathmatch?
