### ISSUE TITLE
[REQ] Several QoL(?) things.

### ISSUE THREAD

**Issue by ItsCEED** [NockyCZ/CS2-Deathmatch#45]
As I can see some stuff is already filtered, here is some more:

Messages:
XX points for neutralizing an enemy with the WEAPON ( I guess it's part of the DM GameMod)
XX points for assisting in neutralizing XXX

Others:
- Disable chat wheel
- Give a weapon from the current config to bots when they try to buy to prevent console spam of "[AI BT]: Unable to buy after multiple attempts." (causes some lag)
- When the timer is less than 60 or 60 seconds make it so it is 00:XX instead of XX
- Database preferences (?)
- In HS mod, when you get shot to the body, you are getting slowed down, a fix for this will be nice since it feels like you are lagging lol
- Make the message box not blink, its annoying on the eyes and defocusing 
![image](https://github.com/NockyCZ/CS2-Deathmatch/assets/20998381/d57cf97c-9180-494d-a305-56b16b15be52)

Some of this changes if possible, will prevent the bloating the server with extra plugins

**Comment by mavproductions** [comment]
Message blinking is when another hud message is trying to hijack priority over DMs persistent timer message. You shouldn't have blinking unless you have warmup permanently on or another plugin is trying to use it. You might also be able to offset the hud message to a different position with `Hud Type` command but I haven't tested it myself.

**Comment by ItsCEED** [comment]
> Message blinking is when another hud message is trying to hijack priority over DMs persistent timer message. You shouldn't have blinking unless you have warmup permanently on or another plugin is trying to use it. You might also be able to offset the hud message to a different position with `Hud Type` command but I haven't tested it myself.

You might be right, but I'm sure I don't have another panel under it or any other trying to take over, maybe is caused by recent updates as I noticed other servers that use the same position begin to have the blinking issues as well.

@NockyCZ 
#Give a weapon from the current config to bots when they try to buy to prevent console spam of "[AI BT]: Unable to buy after multiple attempts." (causes some lag)


Regarding this, I fixed the issue by modding the behavior of the bots, I'm not too sure if can be resolved via the DM plugin or any plugin at all, as the base AI script force the bots to buy no matter what.

**Comment by mavproductions** [comment]
@ItsCEED my server doesn't have the blinking issue currently, on newest CSS + MM versions. I think my server runs a pretty bare plugin allocation on DM-MultiCFG mode in terms of front-end things.

**Comment by mavproductions** [comment]
> > @ItsCEED my server doesn't have the blinking issue currently, on newest CSS + MM versions. I think my server runs a pretty bare plugin allocation on DM-MultiCFG mode in terms of front-end things.
> 
> Do you have timer in your messages?

Yes. In my personal server I use `"CenterMessageText": "<font class='fontSize-2' color='orange'>2nd Round Buy<br>Next Mode: {NEXTMODE} in {REMAININGTIME}</font>",` 

in my `Deathmatch.json` file with no issues.

**Comment by mavproductions** [comment]
Actually sh*t I see what you mean after joining a warmup server. they eliminate the blinking all together. Not the "glitch" I was referring to when another hud msg tries to hijack the DM-multicfg htmlHud msg

---> https://streamable.com/6wu0kz

**Comment by NockyCZ** [comment]
> As I can see some stuff is already filtered, here is some more:
> 
> Messages: XX points for neutralizing an enemy with the WEAPON ( I guess it's part of the DM GameMod) XX points for assisting in neutralizing XXX
> 
> Others:
> 
> * Disable chat wheel
> * Give a weapon from the current config to bots when they try to buy to prevent console spam of "[AI BT]: Unable to buy after multiple attempts." (causes some lag)
> * When the timer is less than 60 or 60 seconds make it so it is 00:XX instead of XX
> * Database preferences (?)
> * In HS mod, when you get shot to the body, you are getting slowed down, a fix for this will be nice since it feels like you are lagging lol
> * Make the message box not blink, its annoying on the eyes and defocusing
>   ![image](https://private-user-images.githubusercontent.com/20998381/342880642-d57cf97c-9180-494d-a305-56b16b15be52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3Njc1MzcsIm5iZiI6MTcxOTc2NzIzNywicGF0aCI6Ii8yMDk5ODM4MS8zNDI4ODA2NDItZDU3Y2Y5N2MtOTE4MC00OTRkLWEzMDUtNTZiMTZiMTViZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE3MDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYmJiOTA0ZmExNjhmY2M2NTVjMDRjZWEwMTJhNGY1NWNjYjEzMDAzYjQ5NzY3NjY0MmM2YjU0OGQyZmZiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uu4J2686JkOV_0-cSPElI91kWusK7B66bN3b2t8Sep0)
> 
> Some of this changes if possible, will prevent the bloating the server with extra plugins

1. Not possible to block these messages right now
2. Yeah it is possible
3. Bots already get weapons at spawn
4. Maybe in the future
5. Yeah it is possible i think
6. Not possible, if you dont want blinking just use Hud Type = 0

**Comment by ItsCEED** [comment]
> > As I can see some stuff is already filtered, here is some more:
> > Messages: XX points for neutralizing an enemy with the WEAPON ( I guess it's part of the DM GameMod) XX points for assisting in neutralizing XXX
> > Others:
> > 
> > * Disable chat wheel
> > * Give a weapon from the current config to bots when they try to buy to prevent console spam of "[AI BT]: Unable to buy after multiple attempts." (causes some lag)
> > * When the timer is less than 60 or 60 seconds make it so it is 00:XX instead of XX
> > * Database preferences (?)
> > * In HS mod, when you get shot to the body, you are getting slowed down, a fix for this will be nice since it feels like you are lagging lol
> > * Make the message box not blink, its annoying on the eyes and defocusing
> >   ![image](https://private-user-images.githubusercontent.com/20998381/342880642-d57cf97c-9180-494d-a305-56b16b15be52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3Njc1MzcsIm5iZiI6MTcxOTc2NzIzNywicGF0aCI6Ii8yMDk5ODM4MS8zNDI4ODA2NDItZDU3Y2Y5N2MtOTE4MC00OTRkLWEzMDUtNTZiMTZiMTViZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE3MDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYmJiOTA0ZmExNjhmY2M2NTVjMDRjZWEwMTJhNGY1NWNjYjEzMDAzYjQ5NzY3NjY0MmM2YjU0OGQyZmZiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uu4J2686JkOV_0-cSPElI91kWusK7B66bN3b2t8Sep0)
> > 
> > Some of this changes if possible, will prevent the bloating the server with extra plugins
> 
> 1. Not possible to block these messages right now
> 2. Yeah it is possible
> 3. Bots already get weapons at spawn
> 4. Maybe in the future
> 5. Yeah it is possible i think
> 6. Not possible, if you dont want blinking just use Hud Type = 0

For the bots, they get random weapon instead the first one (based on what I can see), causing them to draw pistols if what they get is not in their preferences I fixed this for me (partially) with profile editing and script editing by disable buying weapon.

For 6 yes, 0 is the way to go

**Comment by NockyCZ** [comment]
Yeah thats right, in the next version i will add that Default Weapons will also affect bots

**Comment by NockyCZ** [comment]
Added, https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.7
