### ISSUE TITLE
[REQ] Specify bot loadout

### ISSUE THREAD

**Issue by DigitalFriends** [NockyCZ/CS2-Deathmatch#49]
Hey, lovely plugin you got here. 

I would like to see a feature where we could specify the bot loadout separate from the player loadout, i host a couple of servers with very specific config, and the bots are forced to use only a specific weapon on these servers. However, on some of the servers i allow entire categories of guns for the players, for example pistol only, but the bots only use USP-S. 

Is there a possibility we can have this feature added?

**Comment by ItsCEED** [comment]
You can modify your bot profile, extract it from vpk, pack it back, and do it as an override.

**Comment by NockyCZ** [comment]
Bots get weapons according to your settings in Custom Modes, to prevent the bots from having disabled weapons.
