### ISSUE TITLE
How do I integrate it within dathost?

### ISSUE THREAD

**Issue by kriptcs** [NockyCZ/CS2-Deathmatch#51]
Greetings!

I want to add this plug-in to a dathost server. It has CS Sharp v247 and the plug-in seems to work. If I write /ak it gives me an ak. But I am not sure how to start for example FFA mode. Just writing /ffa does not work. There seems to be no /help either to be able to understand. Some help would be much appreciated.

Thank you!

**Comment by NockyCZ** [comment]
Read the docs, just set FreeForAll (FFA) to true in the config
