### ISSUE TITLE
armor will disapper when you've just switched guns

### ISSUE THREAD

**Issue by Soramagic7** [NockyCZ/CS2-Deathmatch#55]
whether or not you had armor before you switched guns, its gonna happening, could u fix it?

**Comment by NockyCZ** [comment]
@Soramagic7 
Windows or linux?

**Comment by Soramagic7** [comment]
@NockyCZ 
it's linux

**Comment by NockyCZ** [comment]
Fixed, https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.7
