### ISSUE TITLE
Player spawns on spawns of another team

### ISSUE THREAD

**Issue by ccsimplyspolit** [NockyCZ/CS2-Deathmatch#59]
Title

**Comment by NockyCZ** [comment]
Are you using default or custom spawns?

**Comment by ccsimplyspolit** [comment]
> Are you using default or custom spawns?

default spawns , they mixed for now. in version 1.16 - that not bugging

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.8
