### ISSUE TITLE
Server crash after switching TEAM when we have    "primary_weapon": "", in custom_modes.json

### ISSUE THREAD

**Issue by rabi07** [NockyCZ/CS2-Deathmatch#6]
Server crash after switching TEAM when we have    "primary_weapon": "", in custom_modes.json

I have 
      "primary_weapon": "",
      "secondary_weapon": "",
 in  custom_modes.json
 
 after selecting gun in CT ,if I try to switch in T I'm unable to join the team and after few second server crashing.
 
 Also if I have this config, it will not changing gun for player, after die he is getting ak4 again ,(see already selected m4 before it)
 
       "primary_weapon": "weapon_ak47",
      "secondary_weapon": "weapon_deagle",
      "allow_select_weapons": true,

**Comment by NockyCZ** [comment]
Try it with the latest version please :)
